"""Stub file for appkit_mantine/maps_navigation.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal

from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from appkit_mantine.maps_base import MapConfigNode

class MapNavigation(MapConfigNode):
    @classmethod
    def create(
        cls,
        *children,
        start_lat: Var[float | int] | float | None = None,
        start_long: Var[float | int] | float | None = None,
        end_lat: Var[float | int] | float | None = None,
        end_long: Var[float | int] | float | None = None,
        profile: Literal["cycling", "driving", "walking"]
        | Var[Literal["cycling", "driving", "walking"] | None]
        | None = None,
        profiles: Var[list[Literal["cycling", "driving", "walking"]] | None]
        | list[Literal["cycling", "driving", "walking"]]
        | None = None,
        routing_url: Var[str | None] | str | None = None,
        alternatives: Var[bool | None] | bool | None = None,
        overview: Literal["false", "full", "simplified"]
        | Var[Literal["false", "full", "simplified"] | None]
        | None = None,
        geometries: Literal["geojson", "polyline", "polyline6"]
        | Var[Literal["geojson", "polyline", "polyline6"] | None]
        | None = None,
        steps: Var[bool | None] | bool | None = None,
        line_color: Var[str | None] | str | None = None,
        line_width: Var[float | int | None] | float | None = None,
        line_opacity: Var[float | int | None] | float | None = None,
        line_dasharray: Var[list[float] | None] | list[float] | None = None,
        fit_bounds: Var[bool | None] | bool | None = None,
        fit_bounds_padding: Var[float | int | None] | float | None = None,
        fit_bounds_max_zoom: Var[float | int | None] | float | None = None,
        fit_bounds_duration_ms: Var[float | int | None] | float | None = None,
        continue_straight: Var[bool | None] | bool | None = None,
        annotations: Var[
            bool
            | list[
                Literal[
                    "datasources", "distance", "duration", "nodes", "speed", "weight"
                ]
            ]
            | None
        ]
        | bool
        | list[
            Literal["datasources", "distance", "duration", "nodes", "speed", "weight"]
        ]
        | None = None,
        exclude: Var[list[str] | None] | list[str] | None = None,
        include_steps: Var[bool | None] | bool | None = None,
        include_geometry: Var[bool | None] | bool | None = None,
        show_end_markers: Var[bool | None] | bool | None = None,
        start_marker_color: Var[str | None] | str | None = None,
        end_marker_color: Var[str | None] | str | None = None,
        marker_radius: Var[float | int | None] | float | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapNavigation:
        """Create the component.

        Args:
            *children: The children of the component.
            start_lat: Latitude of the route start point.
            start_long: Longitude of the route start point.
            end_lat: Latitude of the route end point.
            end_long: Longitude of the route end point.
            profile: Single routing profile (default: ``"driving"``).  Ignored if ``profiles`` is set.
            profiles: no description
            routing_url: Base URL of an OSRM-compatible routing API.  Defaults to the public ``https://router.project-osrm.org`` demo server.
            alternatives: Request alternative routes for the active profile (OSRM ``alternatives``).
            overview: Geometry overview detail level (OSRM ``overview``, default: ``"full"``).
            geometries: no description
            steps: Request turn-by-turn step data from the routing API (OSRM ``steps``).
            line_color: Color of the selected route line (default: ``"#4285F4"``).
            line_width: Width of the selected route line in pixels (default: 5).
            line_opacity: Opacity of the selected route line (default: 0.85).
            line_dasharray: Dash pattern ``[dash length, gap length]`` for the route line.
            fit_bounds: Fit the map viewport to the route bounds once loaded (default: True).
            fit_bounds_padding: Padding in pixels applied when fitting bounds (default: 48).
            fit_bounds_max_zoom: Maximum zoom level to fit bounds to.
            fit_bounds_duration_ms: Animation duration in milliseconds for the fit-bounds transition.
            continue_straight: Forces the route to continue straight at the start point (OSRM option).
            annotations: no description
            exclude: Road classes to exclude from routing.  E.g. ``["motorway"]``; supported values are profile-dependent.
            include_steps: Keep turn-by-turn steps in the published navigation state (default: True).
            include_geometry: Keep full route geometry in the published navigation state (default: True).
            show_end_markers: Render start/end markers at the route endpoints (default: True).
            start_marker_color: Color of the start marker (default: ``"#22c55e"``).
            end_marker_color: Color of the end marker (default: ``"#ef4444"``).
            marker_radius: Radius (size) of the start/end markers (default: 8).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class MapDirectionsPanel(MapConfigNode):
    @classmethod
    def create(
        cls,
        *children,
        title: Var[str | None] | str | None = None,
        empty_text: Var[str | None] | str | None = None,
        show_summary: Var[bool | None] | bool | None = None,
        show_steps: Var[bool | None] | bool | None = None,
        max_height: Var[float | int | None] | float | None = None,
        width: Var[float | int | str | None] | float | str | None = None,
        offset_top: Var[float | int | None] | float | None = None,
        offset_left: Var[float | int | None] | float | None = None,
        dock_below_zoom_controls: Var[bool | None] | bool | None = None,
        zoom_controls_gap_rem: Var[float | int | None] | float | None = None,
        collapsible: Var[bool | None] | bool | None = None,
        initially_collapsed: Var[bool | None] | bool | None = None,
        collapse_direction: Literal["bottom", "top"]
        | Var[Literal["bottom", "top"] | None]
        | None = None,
        position: Literal["bottom-left", "bottom-right", "top-left", "top-right"]
        | Var[Literal["bottom-left", "bottom-right", "top-left", "top-right"] | None]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapDirectionsPanel:
        """Create the component.

        Args:
            *children: The children of the component.
            title: Panel header title (default: ``"Directions"``).
            empty_text: Text shown while no navigation state is available yet.
            show_summary: Show the duration/distance summary for the selected route (default: True).
            show_steps: Show the turn-by-turn step list for the selected route (default: True).
            max_height: Maximum height in pixels of the scrollable panel body.
            width: Panel width (number treated as pixels, or any CSS size string).
            offset_top: Explicit top offset in pixels, overriding the default corner position.
            offset_left: Explicit left offset in pixels, overriding the default corner position.
            dock_below_zoom_controls: Position the panel just below the zoom controls instead of a fixed offset.
            zoom_controls_gap_rem: Gap in rem between the zoom controls and the panel when docked.
            collapsible: Allow collapsing the panel body via its header (default: True).
            initially_collapsed: Whether the panel body starts collapsed.
            collapse_direction: Direction the collapse chevron points when expanded.
            position: Corner of the map to anchor the panel to (default: ``"top-left"``).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""
