"""Stub file for appkit_mantine/maps_layers.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any

from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from appkit_mantine.maps_base import MapComponentBase

class MapRoute(MapComponentBase):
    @classmethod
    def create(
        cls,
        *children,
        coordinates: Var[list[list[float]]] | list[list[float]] | None = None,
        color: Var[str] | str | None = None,
        width: Var[float | int] | float | None = None,
        opacity: Var[float | int] | float | None = None,
        dash_array: Var[list[float]] | list[float] | None = None,
        interactive: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapRoute:
        """Create the component.

        Args:
            *children: The children of the component.
            coordinates: Array of ``[longitude, latitude]`` coordinate pairs.
            color: Line color as a CSS color value (default: ``"#4285F4"``).
            width: Line width in pixels (default: 3).
            opacity: Line opacity from 0 to 1 (default: 0.8).
            dash_array: Dash pattern ``[dash length, gap length]`` for dashed lines.
            interactive: Whether the route responds to mouse events (default: True).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

class MapArc(MapComponentBase):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        curvature: Var[float | int] | float | None = None,
        samples: Var[int] | int | None = None,
        paint: Var[dict[str, Any]] | dict[str, Any] | None = None,
        layout: Var[dict[str, Any]] | dict[str, Any] | None = None,
        hover_paint: Var[dict[str, Any]] | dict[str, Any] | None = None,
        interactive: Var[bool] | bool | None = None,
        before_id: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[Any] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_hover: EventType[Any] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapArc:
        """Create the component.

        Args:
            *children: The children of the component.
            data: Arcs to render.  Each needs a unique ``id`` and ``from``/``to`` as ``[lng, lat]``.
            curvature: How far the arc bows away from a straight line (default: 0.2).
            samples: Points per arc. Higher = smoother (default: 64).
            paint: MapLibre line-layer paint props, merged over sensible defaults.
            layout: MapLibre line-layer layout props (defaults to rounded joins/caps).
            hover_paint: Paint overrides applied to the hovered arc via feature-state.
            interactive: Whether arcs respond to mouse events (default: True).
            before_id: Insert the arc layers before this MapLibre layer id.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_hover: no description
            **props: The props of the component.

        Returns:
            The component."""

class MapGeoJSON(MapComponentBase):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[dict[str, Any] | str] | dict[str, Any] | str | None = None,
        promote_id: Var[str] | str | None = None,
        fill_paint: Var[bool | dict[str, Any]] | bool | dict[str, Any] | None = None,
        line_paint: Var[bool | dict[str, Any]] | bool | dict[str, Any] | None = None,
        fill_hover_paint: Var[dict[str, Any]] | dict[str, Any] | None = None,
        interactive: Var[bool] | bool | None = None,
        before_id: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[Any] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_hover: EventType[Any] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapGeoJSON:
        """Create the component.

        Args:
            *children: The children of the component.
            data: GeoJSON data (FeatureCollection, Feature, Geometry) or a URL to fetch it from.
            promote_id: Feature property to promote to the feature id.  Required for hover feature-state (``fill_hover_paint``) and stable ``on_hover``/``on_click`` payloads.
            fill_paint: Paint for the polygon fill layer. Pass ``False`` to omit the fill layer.
            line_paint: Paint for the outline layer. Pass ``False`` to omit the outline layer.
            fill_hover_paint: Paint merged onto the fill layer for the hovered feature.  Requires ``promote_id``.
            interactive: Whether features respond to mouse events (default: False).
            before_id: Insert the layers before this MapLibre layer id.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_hover: no description
            **props: The props of the component.

        Returns:
            The component."""

class MapClusterLayer(MapComponentBase):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[dict[str, Any] | str] | dict[str, Any] | str | None = None,
        cluster_max_zoom: Var[int] | int | None = None,
        cluster_radius: Var[int] | int | None = None,
        cluster_colors: Var[list[str]] | list[str] | None = None,
        cluster_thresholds: Var[list[int]] | list[int] | None = None,
        point_color: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_cluster_click: EventType[Any] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_point_click: EventType[Any] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> MapClusterLayer:
        """Create the component.

        Args:
            *children: The children of the component.
            data: GeoJSON FeatureCollection data or a URL to fetch GeoJSON from.
            cluster_max_zoom: Maximum zoom level to cluster points on (default: 14).
            cluster_radius: Radius of each cluster in pixels (default: 50).
            cluster_colors: Colors for cluster circles: [small, medium, large].  Default: green/yellow/red.
            cluster_thresholds: Point count thresholds for color/size steps: [medium, large].  Default: [100, 750].
            point_color: Color for unclustered individual points (default: ``"#3b82f6"``).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_point_click: no description
            on_cluster_click: no description
            **props: The props of the component.

        Returns:
            The component."""
