"""Stub file for appkit_mantine/scroll_area.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal

import reflex as rx
from reflex_base.event import (
    EventHandler,
    EventSpec,
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

class ScrollArea(rx.Component):
    @classmethod
    def create(
        cls,
        *children,
        type: Literal["always", "auto", "hover", "never", "scroll"]
        | Var[Literal["always", "auto", "hover", "never", "scroll"]]
        | None = None,
        offset_scrollbars: Literal["present", "x", "y"]
        | Var[Literal["present", "x", "y"] | bool]
        | bool
        | None = None,
        start_scroll_position: Var[dict] | dict | None = None,
        scrollbars: Literal["x", "xy", "y", False]
        | Var[Literal["x", "xy", "y", False]]
        | None = None,
        scrollbar_size: Var[int | str] | int | str | None = None,
        scroll_hide_delay: Var[int] | int | None = None,
        overscroll_behavior: Literal["auto", "contain", "none"]
        | Var[Literal["auto", "contain", "none"]]
        | None = None,
        viewport_ref: Any | Var[Any] | None = None,
        viewport_props: Var[dict] | dict | None = None,
        styles: Var[dict] | dict | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_bottom_reached: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_scroll_position_change: EventType[Any] | None = None,
        on_top_reached: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> ScrollArea:
        """Create the component.

        Args:
            *children: The children of the component.
            type: no description
            offset_scrollbars: no description
            start_scroll_position: no description
            scrollbars: no description
            scrollbar_size: no description
            scroll_hide_delay: no description
            overscroll_behavior: no description
            viewport_ref: no description
            viewport_props: no description
            styles: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_scroll_position_change: no description
            on_top_reached: no description
            on_bottom_reached: no description
            **props: The props of the component.

        Returns:
            The component."""

class ScrollAreaAutosize(ScrollArea):
    @classmethod
    def create(
        cls,
        *children,
        mah: Var[int | str] | int | str | None = None,
        maw: Var[int | str] | int | str | None = None,
        type: Literal["always", "auto", "hover", "never", "scroll"]
        | Var[Literal["always", "auto", "hover", "never", "scroll"]]
        | None = None,
        offset_scrollbars: Literal["present", "x", "y"]
        | Var[Literal["present", "x", "y"] | bool]
        | bool
        | None = None,
        start_scroll_position: Var[dict] | dict | None = None,
        scrollbars: Literal["x", "xy", "y", False]
        | Var[Literal["x", "xy", "y", False]]
        | None = None,
        scrollbar_size: Var[int | str] | int | str | None = None,
        scroll_hide_delay: Var[int] | int | None = None,
        overscroll_behavior: Literal["auto", "contain", "none"]
        | Var[Literal["auto", "contain", "none"]]
        | None = None,
        viewport_ref: Any | Var[Any] | None = None,
        viewport_props: Var[dict] | dict | None = None,
        styles: Var[dict] | dict | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_bottom_reached: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_overflow_change: EventType[Any] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_scroll_position_change: EventType[Any] | None = None,
        on_top_reached: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> ScrollAreaAutosize:
        """Create the component.

        Args:
            *children: The children of the component.
            mah: no description
            maw: no description
            type: no description
            offset_scrollbars: no description
            start_scroll_position: no description
            scrollbars: no description
            scrollbar_size: no description
            scroll_hide_delay: no description
            overscroll_behavior: no description
            viewport_ref: no description
            viewport_props: no description
            styles: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_scroll_position_change: no description
            on_top_reached: no description
            on_bottom_reached: no description
            on_overflow_change: no description
            **props: The props of the component.

        Returns:
            The component."""

class ScrollAreaAutoscroll(ScrollArea):
    @classmethod
    def create(
        cls,
        *children,
        type: Literal["always", "auto", "hover", "never", "scroll"]
        | Var[Literal["always", "auto", "hover", "never", "scroll"]]
        | None = None,
        offset_scrollbars: Literal["present", "x", "y"]
        | Var[Literal["present", "x", "y"] | bool]
        | bool
        | None = None,
        start_scroll_position: Var[dict] | dict | None = None,
        scrollbars: Literal["x", "xy", "y", False]
        | Var[Literal["x", "xy", "y", False]]
        | None = None,
        scrollbar_size: Var[int | str] | int | str | None = None,
        scroll_hide_delay: Var[int] | int | None = None,
        overscroll_behavior: Literal["auto", "contain", "none"]
        | Var[Literal["auto", "contain", "none"]]
        | None = None,
        viewport_ref: Any | Var[Any] | None = None,
        viewport_props: Var[dict] | dict | None = None,
        styles: Var[dict] | dict | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_bottom_reached: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_scroll_position_change: EventType[Any] | None = None,
        on_top_reached: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> ScrollAreaAutoscroll:
        """Create an AutoScroll component.

        Args:
            *children: The children of the component.
            type: no description
            offset_scrollbars: no description
            start_scroll_position: no description
            scrollbars: no description
            scrollbar_size: no description
            scroll_hide_delay: no description
            overscroll_behavior: no description
            viewport_ref: no description
            viewport_props: no description
            styles: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_scroll_position_change: no description
            on_top_reached: no description
            on_bottom_reached: no description
            **props: The props of the component.

        Returns:
            An AutoScroll component."""

    def add_imports(self) -> rx.ImportDict | list[rx.ImportDict]: ...
    def add_hooks(self) -> list[str | Var]: ...

class ScrollAreaWithState(rx.ComponentState):
    @rx.event
    def setup_controls(
        self,
        viewport_id: str,
        wrapper_id: str,
        top_buf: int,
        bottom_buf: int,
        persist_key: str | None = None,
        autoscroll: bool = False,
    ) -> list[EventSpec]: ...
    @classmethod
    def get_component(
        cls,
        *children: Any,
        autoscroll: bool = False,
        bottom_buffer: int = 0,
        bottom_button_text: str = "↓ Bottom",
        button_align: Literal["center", "left", "right"] = "center",
        button_props: dict | None = None,
        controls: Literal["top", "bottom", "top-bottom", "both"] = "top-bottom",
        height: str = "300px",
        offset_scrollbars: bool | Literal["x", "y", "present"] = True,
        overscroll_behavior: Literal["contain", "auto", "none"] | None = None,
        persist_key: str | None = None,
        scroll_hide_delay: int = 300,
        scrollbar_size: str | int = "0.75rem",
        scrollbars: Literal[False, "x", "y", "xy"] = "xy",
        show_controls: bool = True,
        start_scroll_position: dict | Var | None = None,
        top_buffer: int = 0,
        top_button_text: str = "↑ Top",
        type: Literal["auto", "scroll", "always", "hover", "never"] = "auto",
        viewport_id: str | None = None,
        viewport_props: dict | None = None,
        on_bottom_reached: EventHandler[rx.event.no_args_event_spec] = None,
        on_top_reached: EventHandler[rx.event.no_args_event_spec] = None,
        **props: Any,
    ) -> rx.Component: ...

class ScrollAreaNamespace(rx.ComponentNamespace):
    autosize = staticmethod(ScrollAreaAutosize.create)
    autoscroll = staticmethod(ScrollAreaAutoscroll.create)
    stateful = staticmethod(ScrollAreaWithState.create)

    @staticmethod
    def __call__(
        *children,
        type: Literal["always", "auto", "hover", "never", "scroll"]
        | Var[Literal["always", "auto", "hover", "never", "scroll"]]
        | None = None,
        offset_scrollbars: Literal["present", "x", "y"]
        | Var[Literal["present", "x", "y"] | bool]
        | bool
        | None = None,
        start_scroll_position: Var[dict] | dict | None = None,
        scrollbars: Literal["x", "xy", "y", False]
        | Var[Literal["x", "xy", "y", False]]
        | None = None,
        scrollbar_size: Var[int | str] | int | str | None = None,
        scroll_hide_delay: Var[int] | int | None = None,
        overscroll_behavior: Literal["auto", "contain", "none"]
        | Var[Literal["auto", "contain", "none"]]
        | None = None,
        viewport_ref: Any | Var[Any] | None = None,
        viewport_props: Var[dict] | dict | None = None,
        styles: Var[dict] | dict | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_bottom_reached: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_scroll_position_change: EventType[Any] | None = None,
        on_top_reached: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> ScrollArea:
        """Create the component.

        Args:
            *children: The children of the component.
            type: no description
            offset_scrollbars: no description
            start_scroll_position: no description
            scrollbars: no description
            scrollbar_size: no description
            scroll_hide_delay: no description
            overscroll_behavior: no description
            viewport_ref: no description
            viewport_props: no description
            styles: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_scroll_position_change: no description
            on_top_reached: no description
            on_bottom_reached: no description
            **props: The props of the component.

        Returns:
            The component."""

scroll_area = ScrollAreaNamespace()
