"""Stub file for appkit_mantine/tree.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any

from reflex import asset
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

from appkit_mantine.base import MantineComponentBase

_TREE_WRAPPER = asset(path="tree_advanced.jsx", shared=True)
_TREE_WRAPPER_IMPORT = ...

class Tree(MantineComponentBase):
    @classmethod
    def create(
        cls,
        *children,
        allow_drop: Var[bool] | bool | None = None,
        allow_range_selection: Var[bool] | bool | None = None,
        check_on_space: Var[bool] | bool | None = None,
        clear_selection_on_outside_click: Var[bool] | bool | None = None,
        data: Var[list[dict]] | list[dict] | None = None,
        expand_on_click: Var[bool] | bool | None = None,
        expand_on_space: Var[bool] | bool | None = None,
        keep_mounted: Var[bool] | bool | None = None,
        level_offset: Var[int | str] | int | str | None = None,
        multiple: Var[bool] | bool | None = None,
        render_node: Any | Var[Any] | None = None,
        select_on_click: Var[bool] | bool | None = None,
        tree: Var[str] | str | None = None,
        value: Var[str] | str | None = None,
        with_drag_handle: Var[bool] | bool | None = None,
        with_lines: Var[bool] | bool | None = None,
        search: Var[str] | str | None = None,
        with_checkbox: Var[bool] | bool | None = None,
        with_custom_node: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> Tree:
        """Create the component.

        Args:
            *children: The children of the component.
            allow_drop: Properties
            allow_range_selection: no description
            check_on_space: no description
            clear_selection_on_outside_click: no description
            data: no description
            expand_on_click: no description
            expand_on_space: no description
            keep_mounted: no description
            level_offset: no description
            multiple: no description
            render_node: no description
            select_on_click: no description
            tree: no description
            value: no description
            with_drag_handle: no description
            with_lines: no description
            search: Enhanced wrapper properties
            with_checkbox: no description
            with_custom_node: no description
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component."""

tree = Tree.create
