"""add required_role to image generator model

Revision ID: e2ed9f7ab897
Revises: g0h1i2j3k4l5
Create Date: 2026-02-16 22:25:19.694153

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e2ed9f7ab897"
down_revision: str | None = "g0h1i2j3k4l5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
