from appkit_assistant.roles import (
    ASSISTANT_ADMIN_ROLE,
    ASSISTANT_ADVANCED_MODELS_ROLE,
    ASSISTANT_BASIC_MODELS_ROLE,
    ASSISTANT_FILE_UPLOAD_ROLE,
    ASSISTANT_PERPLEXITY_MODEL_ROLE,
    ASSISTANT_USER_ROLE,
    ASSISTANT_WEB_SEARCH_ROLE,
)
from appkit_commons.roles import Role

IMAGE_GENERATOR_GROUP = "Bildgenerator"

IMAGE_GENERATOR_ROLE = Role(
    id=2,
    name="image_generator",
    label="Bildgenerator",
    description="Berechtigung für die Bildgenerierung",
    group=IMAGE_GENERATOR_GROUP,
)

ALL_ROLES: list[Role] = [
    ASSISTANT_USER_ROLE,
    ASSISTANT_BASIC_MODELS_ROLE,
    ASSISTANT_ADVANCED_MODELS_ROLE,
    ASSISTANT_PERPLEXITY_MODEL_ROLE,
    ASSISTANT_FILE_UPLOAD_ROLE,
    ASSISTANT_WEB_SEARCH_ROLE,
    ASSISTANT_ADMIN_ROLE,
    IMAGE_GENERATOR_ROLE,
]
