"""Stub file for appkit_ui/components/editor.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
import enum
from collections.abc import Mapping, Sequence
from typing import Any, Literal

from pydantic import BaseModel
from reflex.components.component import NoSSRComponent
from reflex.utils.imports import ImportDict
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

class EditorButtonList(list, enum.Enum):
    BASIC = ...
    FORMATTING = ...
    COMPLEX = ...

class EditorOptions(BaseModel):
    default_tag: str | None
    mode: str | None
    rtl: bool | None
    button_list: list[list[str] | str] | None

def on_blur_spec(_e: Var, content: Var[str]) -> tuple[Var[str]]: ...
def on_paste_spec(
    _e: Var, clean_data: Var[str], max_char_count: Var[bool]
) -> tuple[Var[str], Var[bool]]: ...

class Editor(NoSSRComponent):
    def add_imports(self) -> ImportDict: ...
    @classmethod
    def create(
        cls,
        *children,
        lang: Literal[
            "ckb",
            "da",
            "de",
            "en",
            "es",
            "fr",
            "he",
            "it",
            "ja",
            "ko",
            "lv",
            "pl",
            "pt_br",
            "ro",
            "ru",
            "se",
            "ua",
            "zh_cn",
        ]
        | Var[
            Literal[
                "ckb",
                "da",
                "de",
                "en",
                "es",
                "fr",
                "he",
                "it",
                "ja",
                "ko",
                "lv",
                "pl",
                "pt_br",
                "ro",
                "ru",
                "se",
                "ua",
                "zh_cn",
            ]
            | dict
        ]
        | dict
        | None = None,
        name: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        width: Var[str] | str | None = None,
        height: Var[str] | str | None = None,
        placeholder: Var[str] | str | None = None,
        auto_focus: Var[bool] | bool | None = None,
        set_options: Var[dict] | dict | None = None,
        set_all_plugins: Var[bool] | bool | None = None,
        set_contents: Var[str] | str | None = None,
        append_contents: Var[str] | str | None = None,
        set_default_style: Var[str] | str | None = None,
        disable: Var[bool] | bool | None = None,
        hide: Var[bool] | bool | None = None,
        hide_toolbar: Var[bool] | bool | None = None,
        disable_toolbar: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | EventType[str] | None = None,
        on_change: EventType[()] | EventType[str] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_copy: EventType[()] | None = None,
        on_cut: EventType[()] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_input: EventType[()] | None = None,
        on_load: EventType[()] | EventType[bool] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_paste: EventType[()] | EventType[str] | EventType[str, bool] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        toggle_code_view: EventType[()] | EventType[bool] | None = None,
        toggle_full_screen: EventType[()] | EventType[bool] | None = None,
        **props,
    ) -> Editor:
        """Create an instance of Editor. No children allowed.

        Args:
            set_options: Configuration object to further configure the instance.
            lang: Language of the editor. Alternatively to a string, a dict of your language can be passed to this prop. Please refer to the library docs for this. options: "en" | "da" | "de" | "es" | "fr" | "ja" | "ko" | "pt_br" | "ru" | "zh_cn" | "ro" | "pl" | "ckb" | "lv" | "se" | "ua" | "he" | "it" default: "en".
            name: This is used to set the HTML form name of the editor. This means on HTML form submission, it will be submitted together with contents of the editor by the name provided.
            default_value: Sets the default value of the editor. This is useful if you don't want the on_change method to be called on render. If you want the on_change method to be called on render use the set_contents prop
            width: Sets the width of the editor. px and percentage values are accepted, eg width="100%" or width="500px" default: 100%
            height: Sets the height of the editor. px and percentage values are accepted, eg height="100%" or height="100px"
            placeholder: Sets the placeholder of the editor.
            auto_focus: Should the editor receive focus when initialized?
            set_options: Pass an EditorOptions instance to modify the behaviour of Editor even more.
            set_all_plugins: Whether all SunEditor plugins should be loaded. default: True.
            set_contents: Set the content of the editor. Note: To set the initial contents of the editor without calling the on_change event, please use the default_value prop. set_contents is used to set the contents of the editor programmatically. You must be aware that, when the set_contents's prop changes, the on_change event is triggered.
            append_contents: Append editor content
            set_default_style: Sets the default style of the editor's edit area
            disable: Disable the editor default: False.
            hide: Hide the editor default: False.
            hide_toolbar: Hide the editor toolbar default: False.
            disable_toolbar: Disable the editor toolbar default: False.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when the editor loses focus.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: Fired when the editor content changes.
            on_input: Fired when the something is inputted in the editor.
            on_load: Fired when the editor is loaded.
            on_copy: Fired when the editor content is copied.
            on_cut: Fired when the editor content is cut.
            on_paste: Fired when the editor content is pasted.
            toggle_code_view: Fired when the code view is toggled.
            toggle_full_screen: Fired when the full screen mode is toggled.
            **props: Any properties to be passed to the Editor

        Returns:
            An Editor instance.

        Raises:
            ValueError: If set_options is a state Var."""

editor = Editor.create
